<?php
/**
 * Model for clientes
 * 
 * Generated by BlackPHP
 */

class clientesModel
{
	use ORM;

	/** @var int $cliente_id Llave primaria */
	private $cliente_id;

	/** @var int $entity_id ID de la entidad */
	private $entity_id;

	/** @var string $nombre Nombre del cliente */
	private $nombre;

	/** @var string $direccion Dirección del cliente */
	private $direccion;

	/** @var string $telefono Teléfono del cliente */
	private $telefono;

	/** @var string $fecha_nacimiento Fecha de nacimiento */
	private $fecha_nacimiento;

	/** @var int $creation_user - */
	private $creation_user;

	/** @var string $creation_time - */
	private $creation_time;

	/** @var int $edition_user - */
	private $edition_user;

	/** @var string $edition_time - */
	private $edition_time;

	/** @var int $status - */
	private $status;


	/** @var string $_table_name Nombre de la tabla */
	private static $_table_name = "clientes";

	/** @var string $_table_type Tipo de tabla */
	private static $_table_type = "BASE TABLE";

	/** @var string $_primary_key Llave primaria */
	private static $_primary_key = "cliente_id";

	/** @var bool $_timestamps La tabla usa marcas de tiempo para la inserción y edición de datos */
	private static $_timestamps = true;

	/** @var bool $_soft_delete La tabla soporta borrado suave */
	private static $_soft_delete = true;

	/** @var int|null $_deleted_status Valor a asignar en caso de borrado suave. */
	private static $_deleted_status = 0;

	/**
	 * Constructor de la clase
	 * 
	 * Se inicializan las propiedades de la clase.
	 * @param bool $default Determina si se utilizan, o no, los valores por defecto
	 * definidos en la base de datos.
	 **/
	public function __construct($default = true)
	{
		if($default)
		{
			$this->status = 1;
		}
	}

	public function getClienteId()
	{
		return $this->cliente_id;
	}

	public function setClienteId($value)
	{
		$this->cliente_id = $value === null ? null : (int)$value;
	}

	public function getEntityId()
	{
		return $this->entity_id;
	}

	public function setEntityId($value)
	{
		$this->entity_id = $value === null ? null : (int)$value;
	}

	public function getNombre()
	{
		return $this->nombre;
	}

	public function setNombre($value)
	{
		self::validateStringSize($value, 128);
		$this->nombre = $value === null ? null : (string)$value;
	}

	public function getDireccion()
	{
		return $this->direccion;
	}

	public function setDireccion($value)
	{
		self::validateStringSize($value, 255);
		$this->direccion = $value === null ? null : (string)$value;
	}

	public function getTelefono()
	{
		return $this->telefono;
	}

	public function setTelefono($value)
	{
		self::validateStringSize($value, 16);
		$this->telefono = $value === null ? null : (string)$value;
	}

	public function getFechaNacimiento()
	{
		return $this->fecha_nacimiento;
	}

	public function setFechaNacimiento($value)
	{
		$this->fecha_nacimiento = $value === null ? null : (string)$value;
	}

	public function getCreationUser()
	{
		return $this->creation_user;
	}

	public function setCreationUser($value)
	{
		$this->creation_user = $value === null ? null : (int)$value;
	}

	public function getCreationTime()
	{
		return $this->creation_time;
	}

	public function setCreationTime($value)
	{
		$this->creation_time = $value === null ? null : (string)$value;
	}

	public function getEditionUser()
	{
		return $this->edition_user;
	}

	public function setEditionUser($value)
	{
		$this->edition_user = $value === null ? null : (int)$value;
	}

	public function getEditionTime()
	{
		return $this->edition_time;
	}

	public function setEditionTime($value)
	{
		$this->edition_time = $value === null ? null : (string)$value;
	}

	public function getStatus()
	{
		return $this->status;
	}

	public function setStatus($value)
	{
		$this->status = $value === null ? null : (int)$value;
	}
}
?>
